apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dashi-data
resources:
  - namespace.yaml
  - statefulset-postgres.yaml
  - deployment-server.yaml
  - service.yaml
  - rbac.yaml
  - deployment-worker.yaml
labels:
  - pairs:
      app.kubernetes.io/part-of: dashi
    includeSelectors: false
