apiVersion: v1
kind: Service
metadata:
  name: prefect-server
  namespace: miso-data
  labels:
    app.kubernetes.io/name: prefect-server
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: prefect-server
  ports:
    - name: api
      port: 4200
      targetPort: api
