apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dashi-serving-db
resources:
  - namespace.yaml
  - statefulset.yaml
labels:
  - pairs:
      app.kubernetes.io/part-of: dashi
    includeSelectors: false
