apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dashi-catalog
resources:
  - namespace.yaml
  - secret.yaml
  - statefulset-postgres.yaml
  - service-postgres.yaml
  - job-migrate.yaml
  - deployment-stac-api.yaml
  - service-stac-api.yaml
labels:
  - pairs:
      app.kubernetes.io/part-of: dashi
    includeSelectors: false
