apiVersion: v1
kind: Service
metadata:
  name: stac-fastapi
  namespace: dashi-catalog
  labels:
    app.kubernetes.io/name: stac-fastapi
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: stac-fastapi
  ports:
    - name: http
      port: 8080
      targetPort: http
