apiVersion: v1
kind: Service
metadata:
  name: pgstac
  namespace: miso-catalog
  labels:
    app.kubernetes.io/name: pgstac
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: pgstac
  ports:
    - name: pg
      port: 5432
      targetPort: pg
---
apiVersion: v1
kind: Service
metadata:
  name: pgstac-headless
  namespace: miso-catalog
  labels:
    app.kubernetes.io/name: pgstac
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: pgstac
  ports:
    - name: pg
      port: 5432
      targetPort: pg
