apiVersion: v1
kind: Service
metadata:
  name: titiler
  namespace: dashi-serving
  labels:
    app.kubernetes.io/name: titiler
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: titiler
  ports:
    - name: http
      port: 8080
      targetPort: http
