apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dashi-platform
resources:
  - namespace.yaml
  - secret.yaml
  - statefulset.yaml
  - service.yaml
  - job-buckets.yaml
labels:
  - pairs:
      app.kubernetes.io/part-of: dashi
    includeSelectors: false
