apiVersion: v1
kind: Service
metadata:
  name: rustfs
  namespace: miso-platform
  labels:
    app.kubernetes.io/name: rustfs
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: rustfs
  ports:
    - name: s3
      port: 9000
      targetPort: s3
    - name: console
      port: 9001
      targetPort: console
---
apiVersion: v1
kind: Service
metadata:
  name: rustfs-headless
  namespace: miso-platform
  labels:
    app.kubernetes.io/name: rustfs
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: rustfs
  ports:
    - name: s3
      port: 9000
      targetPort: s3
