apiVersion: v1
kind: Service
metadata:
  name: tipg
  namespace: dashi-serving
  labels:
    app.kubernetes.io/name: tipg
    app.kubernetes.io/part-of: dashi
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: tipg
  ports:
    - name: http
      port: 8081
      targetPort: http
